blog/urls.py
from django.conf.urls.static import static
from django.urls import path
from .import views
from django.conf import settings

app_name = 'blog'
urlpatterns =[
    path('', views.index, name='home'),
    path('course/', views.CourseList.as_view(), name='course_list'),
    path('event/', views.EventList.as_view(), name='event_list'),
    path('blog/', views.BlogList.as_view(), name='blog_list'),
    path('<int:pk>/', views.BlogDetailView.as_view(), name='detail'),
    path('<int:pk>/event/', views.EventDetailView.as_view(), name='event_detail'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

kh_brochure/urls.py
from django.contrib import admin
from django.urls import include,  path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.db import models
from django.template.defaultfilters import slugify

# Register your models here.
class Blog(models.Model):
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=500)
    content = models.TextField()
    blog_image = models.FileField(upload_to='uploads')
    author = models.CharField(max_length=200)
    pub_date = models.DateTimeField('published date')
    slug = models.SlugField(max_length=200)

    def __str__(self):
      return self.title

    def slug(self):
        return slugify(self.title)

class Course(models.Model):
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=250)
    body = models.TextField()
    course_image = models.FileField(upload_to='uploads')

    def __str__(self):
      return self.title

class Event(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    description = models.CharField(max_length=250, default=None, blank=True, null=True)
    event_image = models.FileField(upload_to='uploads')
    event_date = models.DateTimeField('Event Date')
    created_at = models.DateTimeField('published date')

    def __str__(self):
      return self.title

blog/views.py
from django.shortcuts import render
from django.views import generic
# Create your views here.
from django.utils import timezone
from .models import Blog, Course, Event


def index(request):
    latest_blog_list = Blog.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:4:]
    course_list = Course.objects.all()[:4]
    event_list = Event.objects.all()[:4]
    context = {'latest_blog_list': latest_blog_list, 'course_list': course_list, 'event_list': event_list}
    return render(request, 'brochure/home.html', context)


class BlogList(generic.ListView):
    template_name = 'brochure/all_blog.html'
    context_object_name = 'latest_blog_list'

    def get_queryset(self):
        return Blog.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:10]


class BlogDetailView(generic.DetailView):
    model = Blog
    template_name = 'brochure/detail.html'
    slug_field = 'title'
    slug_url_kwarg = 'title'


class CourseList(generic.ListView):
    template_name = 'brochure/course.html'
    context_object_name = 'course_list'

    def get_queryset(self):
        return Course.objects.all()[:4:]


class EventList(generic.ListView):
    template_name = 'brochure/event_list.html'
    context_object_name = 'event_list'

    def get_queryset(self):
        return Event.objects.all()[:4:]

class EventDetailView(generic.DetailView):
    model = Event
    template_name = 'brochure/event_detail.html'

blog/templates/brochure/all_blog.html
{% extends 'brochure/base.html' %}
{% load static %}

{% block body %}

<div class="container">
    <h3 class="course-title"><b>Our Blogs</b></h3>
    {% if latest_blog_list %}
    {% for blog in latest_blog_list %}
    <div class="row">
        <div class="col-sm-2">
            <img class="card-img-top img-item" src="{{blog.blog_image.url }}" alt="Card image cap">
        </div>
        <div class="col-sm-4">
            <h5 class="card-title title-item"><a href="{% url 'blog:detail' blog.id %}">{{ blog.title }}</a></h5>
            <p class="card-text">{{blog.description}}</p>
            <p class="card-text">{{blog.pub_date}}</p>
            <hr>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <p>No blog available check back again</p>
    {% endif %}
</div>
{% endblock %}

blog/templates/brochure/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'>
    <link rel="stylesheet" href="{% static 'brochure/css/style.css' %}" type="text/css"/>
    <title>Brochure App</title>
</head>
<body>
<nav class="navbar navbar-expand-lg nav-bar">
        <a class="navbar-brand" href="{% url 'blog:home' %}">KODEHAUZ</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon toggle-icon">
                <div></div>
                <div></div>
                <div></div>
            </span>
        </button>
        <div class="collapse navbar-collapse right" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link nav-text" href="{% url 'blog:home' %}">About <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link nav-text" href="{% url 'blog:course_list' %}">Courses</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link nav-text" href="{% url 'blog:blog_list' %}">Blog</a>
                </li>
                 <li class="nav-item">
                    <a class="nav-link nav-text" href="{% url 'blog:event_list' %}">Events</a>
                </li>
            </ul>
        </div>
    </nav>
{% block body %}

{% endblock %}

{% include 'brochure/footer.html' %}

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>

blog/templates/brochure/course.html
{% extends 'brochure/base.html' %}
{% load static %}

{% block body %}

<div class="container">
    <h3 class="course-title"><b>Our Courses</b></h3>
    {% if course_list %}
    {% for course in course_list %}
    <div class="row courseList-item">
        <div class="col-sm-6">
            <img class="card-img-top img-item" src="{{course.course_image.url }}" alt="Card image cap">
        </div>
        <div class="col-sm-6">
            <h5 class="card-title title-item">{{course.title}}</h5>
            <p class="card-text">{{course.body}}</p>
            <hr>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <p>No course available</p>
    {% endif %}
</div>
{% endblock %}

blog/templates/brochure/detail.html
{% extends 'brochure/base.html' %}

{% load static %}
{% block body %}
<div class="row">
    <div class="col-sm-12 blog-detail">
        <img src="{{blog.blog_image.url}}" width="300px" height="300px" alt="blog image">
        <h3 class="blog-title">{{blog.title}}</h3>
        <h5>{{blog.content}}</h5>
        <label>Written by:</label><label class="author">{{blog.author}}</label>
        <p>{{blog.pub_date}}</p>
        {% if error_message %} <p><strong>{{error_message}}</strong></p>{% endif %}
    </div>
</div>

{% endblock %}

blog/templates/brochure/event_detail.html
{% extends 'brochure/base.html' %}

{% load static %}
{% block body %}
<div class="row">
    <div class="col-sm-12 blog-detail">
        <img src="{{event.event_image.url}}" width="300px" height="300px" alt="event image">
        <h3 class="blog-title">{{event.title}}</h3>
        <h5>{{event.content}}</h5>
        <label>Event date:</label><label class="author">{{event.event_date}}</label>
        {% if error_message %} <p><strong>{{error_message}}</strong></p>{% endif %}
    </div>
</div>

{% endblock %}

blog/templates/brochure/event_list.html
{% extends 'brochure/base.html' %}
{% load static %}

{% block body %}

<div class="container">
    <h3 class="course-title"><b>Upcoming Events</b></h3>
    {% if event_list %}
    {% for event in event_list %}
    <div class="row">
        <div class="col-sm-2">
            <img class="card-img-top img-item" src="{{event.event_image.url }}" alt="Card image cap">
        </div>
        <div class="col-sm-4">
            <h5 class="card-title title-item"><a href="{% url 'blog:event_detail' event.id %}">{{ event.title }}</a>
            </h5>
            <p class="card-text">{{event.description}}</p>
            <p class="card-text">{{event.event_ate}}</p>
            <hr>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <p>No event available check back again</p>
    {% endif %}
</div>
{% endblock %}

blog/templates/brochure/footer.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'brochure/css/style.css' %}" type="text/css">


    <title>Brochure</title>
</head>
<body>
<!-- Footer -->
<footer class="page-footer font-small teal pt-4 my-footer">

    <!-- Footer Text -->
    <div class="container-fluid text-center text-md-left">

        <!-- Grid row -->
        <div class="row">

            <!-- Grid column -->
            <div class="col-md-4 mt-md-0 mt-3">
                <!-- Content -->
                <h5 class="text-uppercase font-weight-bold">KODEHAUZ BROCHURE</h5>
                <p>2019 &copy; Copyright All rights reserved</p>
            </div>
            <!-- Grid column -->

            <hr class="clearfix w-100 d-md-none pb-3">

            <!-- Grid column -->
            <div class="col-md-4 mb-md-0 mb-3">
                <!-- Content -->
                <h5 class="text-uppercase font-weight-bold">Contact us</h5>
                <p>Office Address: KodeHauz</p>
                <p>38, Afaha Uqua Road, Eket Akwa Ibom State</p>
            </div>

            <!-- Grid column -->
            <div class="col-md-4 mb-md-0 mb-3">
                <!-- Content -->
                <h5 class="text-uppercase font-weight-bold">Socials</h5>
                    <span class="dot">
                        <label ><i class="fa fa-facebook facebook" style="font-size:24px"></i></label>
                    </span>
                 <span class="dot">
                    <label ><i class="fa fa-twitter twitter" style="font-size:24px"></i></label>
                 </span>
                 <span class="dot">
                    <label ><i class="fa fa-linkedin linkedin" style="font-size:24px"></i></label>
                 </span>
            </div>
            <!-- Grid column -->
        </div>
        <!-- Grid row -->
    </div>
    <!-- Footer Text -->
</footer>
<!-- Footer -->

</body>
</html>

blog/templates/brochure/home.html
{% extends 'brochure/base.html' %}
{% load static %}

{% block body %}
<div>
    <div class="row top-row">
        <div class="d-none d-sm-block col-sm-6 first-half">
        </div>
        <div class="col-sm-6 top-half">
            <h2><b>KodeHauz Institute <br>Brochure</b></h2>

            <div class="sub-text">This brochure gives you the details of our services <br> and available training
                programs.
            </div>

            <div style="display: table; margin-top: 48px;">
                <div class="get-started">
                    <div class="our-services">
                        <div class="arrow-left"></div>
                    </div>
                    <div class="started"><a href="{% url 'blog:course_list' %}"><b style="margin-left: 24px;">GET STARTED</b></a></div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <h3 class="what-we-do">What we do</h3>
        <div class="row">
            <div class="col-md-4">
                <h5>Software as a <br> Service</h5>
                <img class="circle-image" src="{% static 'brochure/images/kodehauz.png' %}" alt="kodeahuauz">
                <p>We provide software solutions <br>that we meet your everyday <br> and future needs</p>
            </div>

            <div class="col-md-4">
                <h5>Software <br> Training</h5>
                    <img class="circle-image" src="{% static 'brochure/images/kodehauz.png' %}" alt="kodeahuauz">
                <p>We provide software solutions <br>that we meet your everyday <br> and future needs</p>
            </div>
            <div class="col-md-4">
                <h5>Business Training and <br> Development</h5>
                    <img class="circle-image" src="{% static 'brochure/images/kodehauz.png' %}" alt="kodeahuauz">
                <p>We provide software solutions <br>that we meet your everyday <br> and future needs</p>
            </div>
        </div>
    </div>
    <div class="courses-section">
        <h3 class="course-title"><b>Our Courses</b></h3>
        <div class="row">
            {% if course_list %}
            {% for course in course_list %}
            <div class="col-sm-3">
                <div class="card course-card">
                    <img class="card-img-top" src="{{course.course_image.url }}"
                          alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">{{ course.title }}</h5>
                        <p class="card-text">{{course.description}}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <p>No course available check back again</p>
            {% endif %}
        </div>
        <div style="text-align: center;">
            <button type="button" class="btn btn-primary all-courses">
                <a class="nav-link" href="{% url 'blog:course_list' %}">DETAILS</a></button>
        </div>
    </div>
    <div class="upcoming-events">
        <h3 class="event-title">Upcoming Events</h3>
        <div class="row">
            {% if event_list %}
            {% for event in event_list %}
            <div class="col-sm-1 col-xs-1 event-time offset-md-1">
                <p>{{event.event_date}}</p>
            </div>
            <div class="col-sm-4">
                <h4 class="event-text"><a href="{% url 'blog:event_detail' event.id %}">{{ event.title }}</a></h4>
                <h6 class="event-text">{{event.description}}</h6>
                <hr style="width: 100%;">

            </div>
            {% endfor %}
            {% else %}
            <p>There is no upcoming event</p>
            {% endif %}
        </div>
        <div style="text-align: center;">
            <button type="button" class="btn btn-primary all-courses">
                <a class="nav-link" href="{% url 'blog:event_list' %}">VIEW ALL</a></button>
        </div>
    </div>
    <div class="blog-section">
        <h3 class="course-title"><b>Our Blog</b></h3>
        <div class="row">
            {% if latest_blog_list %}
            {% for blog in latest_blog_list %}
            <div class="col-sm-3 blog-card">
                <div class="card">
                    <img class="card-img-top" src="{{ blog.blog_image.url }}"
                         width="200px" height="200px" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title"><a href="{% url 'blog:detail' blog.id %}">{{ blog.title }}</a></h5>
                        <p class="card-text">{{blog.description}}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <p>No blog available check back again</p>
            {% endif %}
        </div>
        <div style="text-align: center;">
            <button type="button" class="btn btn-primary all-courses"><a class="nav-link" href="{% url 'blog:blog_list' %}">VIEW ALL</a>
            </button>
        </div>
    </div>
</div>
{% endblock %}